apiVersion: v1
kind: Service
metadata:
  # namespace: ngnix-demo
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80
  externalTrafficPolicy: Cluster