apiVersion: v1
kind: Service
metadata:
  # namespace: ngnix-demo
  name: nginx-service
spec:
  selector:
    app: ngnix
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80