apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: ngnix
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
